# values.yaml
replicaCount: 1
containerPort: 5000

image:
  repository: 637423388059.dkr.ecr.ap-southeast-1.amazonaws.com/evppf/poc-svc-blue
  tag: "latest"
  pullPolicy: IfNotPresent


fullnameOverride: "poc-svc-blue"


env:
  PEER_SERVICES: "green:http://poc-svc-green,yellow:http://poc-svc-yellow"

service:
  type: ClusterIP
  ports: 
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP

istio:
  enabled: true
  gatewayName: "argocd-gateway"
  host: "blue.local"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"